title: Wander
description: A worldbuilding project involving getting lost and finding treasure in the farthest corners of reality.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: "/wander" # the subpath of your site, e.g. /blog
url: "https://curious-robot.github.io" # the base hostname & protocol for your site
collections:
  pathways:
    output: true
    permalink: /:collection/:name/
  concepts:
    output: true
  timelines:
    output: true
  goi:
    output: true
collections_dir: collections