title: Wander
description: A worldbuilding project involving getting lost and finding treasure in the farthest corners of reality.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: "wander" # the subpath of your site, e.g. /blog
url: "https://curious-robot.github.io/" # the base hostname & protocol for your site
collections:
- pathways
- concepts
- timelines
- goi
collections_dir: collections